- name: Find and Replace Action
  # You may pin to the exact commit or the version.
  # uses: nguyenvanuyn96/str-find-and-replace-action@c00a9cd8c5e4323363a1d5907e15c3a2b4ed9698
  uses: nguyenvanuyn96/str-find-and-replace-action@0.0.5
  with:
    # A regular expression of files to include in our find and replace
    include: # optional, default is .*
    # A regular expression of files to exclude in our find and replace
    exclude: # optional, default is .git
    # The string we want to replace
    find: 
    # The new string to replace with
    replace: 
